"""Extract the August batch P&L from the TMC profitability workbook into data/data.js.

Usage: python3 scripts/extract_data.py <path-to-workbook.xlsx>

Only batch-level figures and the aggregate operations-salary pool are exported;
individual payroll lines are deliberately left out.
"""
import json
import sys

import openpyxl

wb = openpyxl.load_workbook(sys.argv[1], data_only=True)
pl, rev, cogs, pay = wb["Batch P&L"], wb["Revenue"], wb["Cogs"], wb["Payroll Sheet"]

rev_rows = {}
for r in range(6, 28):
    bid = rev[f"B{r}"].value
    if bid:
        rev_rows[bid] = r
cogs_rows = {cogs[f"B{r}"].value: r for r in range(6, 26) if cogs[f"B{r}"].value}

batches = []
for r in range(5, 25):
    bid = pl[f"A{r}"].value
    rr, cr = rev_rows[bid], cogs_rows[bid]
    batches.append({
        "id": bid,
        "client": pl[f"B{r}"].value.strip(),
        "segment": pl[f"C{r}"].value,
        "teacher": pl[f"D{r}"].value.strip(),
        "teacherType": pl[f"E{r}"].value,
        "learners": pl[f"F{r}"].value,
        "grossRevenue": pl[f"G{r}"].value,
        "creditNotes": pl[f"H{r}"].value,
        "netRevenue": pl[f"I{r}"].value,
        "teacherCost": pl[f"J{r}"].value,
        "opsCost": pl[f"K{r}"].value,
        "start": rev[f"D{rr}"].value.strftime("%Y-%m-%d"),
        "end": rev[f"E{rr}"].value.strftime("%Y-%m-%d"),
        "feePerLearner": rev[f"G{rr}"].value,
        "courseDays": rev[f"H{rr}"].value,
        "augDays": rev[f"I{rr}"].value,
        "contractValue": rev[f"K{rr}"].value,
        "courseHours": cogs[f"J{cr}"].value,
        "augHours": cogs[f"K{cr}"].value,
        "hourlyRate": cogs[f"N{cr}"].value if isinstance(cogs[f"N{cr}"].value, (int, float)) else None,
    })

ops_payroll = sum(pay[f"E{r}"].value or 0 for r in range(5, 34)
                  if (pay[f"D{r}"].value or "").strip() == "Operations Salaries")
ft_charged = sum(b["teacherCost"] for b in batches if b["teacherType"] == "Full Time")

data = {
    "month": "August 2026",
    "currency": "Rs",
    "groupNote": "Group includes Somika & Vinmart",
    "opsPayroll": ops_payroll,
    "ftTeacherCostInCogs": ft_charged,
    "opsPool": pl["Q7"].value,
    "batches": batches,
}
with open("data/data.js", "w") as f:
    f.write("// Generated by scripts/extract_data.py from the August profitability workbook.\n")
    f.write("window.TMC_DATA = " + json.dumps(data, indent=1) + ";\n")
print(len(batches), ops_payroll, ft_charged, data["opsPool"])
